# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 9.x, 10.x, 12.x]

    steps:
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql db: 'pubg'
        postgresql password: 'pub'
        postgresql user: 'pubg'
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --ignore-optional --no-node-version-check
    - run: yarn test
      env:
        PGUSER: pubg
        PGHOST: 0.0.0.0
        PGDATABASE: pubg
        PGPASSWORD: pubg
